### ISSUE TITLE
Build iqtree2core library using pybind11 

### ISSUE THREAD

**Issue by khiron** [cogent3/iqtree2_serialization#22]
iqtree2core target generates a  shared library (.so on linux, .dll on windows) 
exports 
  std::string getIqTreeVersion();
  void set_params(const std::string& json_str);
  std::string get_params();
  std::string get_param(const std::string& name);
  void generate_random_tree(const std::string& json_str);
  
source for iqtree2core is in /core folder 

The python library that imports the shared library is in /piqtree2/piqtree2

/piqtree2/piqtree2/libs/test_iqtree2core_connectivity.py is a sample python program that simply tests connectivity to the shared library in the same directory.  So build the shared library and copy it into the libs directory and run 

python -m test_iqtree2core_connectivity.py

Result is 

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/iqtree2/piqtree2/libs/test_iqtree2core_connectivity.py", line 2, in <module>
    import iqtree2core
ImportError: /iqtree2/piqtree2/libs/iqtree2core.so: undefined symbol: _ZN9PhyloTree21setParsimonyKernelAVXEv

The problem appears to be that the iqtree2core project is not built with the AVX libraries.

**Comment by thomaskf** [comment]
Hi Richard,

I have made some changes (committed on Dec 22, 2023) to address several "undefined symbol" issues due to the IQTREE codes.

However, now there is another issue (after running `python -m test_iqtree2core_connectivity.py`):

"ImportError: dynamic module does not define module export function (PyInit_iqtree2core)"

I think this issue is not related to the IQTREE codes. Thus, I am now passing it back to you to handle it. Once this issue is solved, if there are more "undefined symbol" issues due to the IQTREE codes, I will continue to work on them.

Thanks,
Thomas
